; J-29 Game Library Example
; folder= controls the virtual directory shown under GAMES/

[GAME1]
name=NOTEPAD
path=notepad.exe
folder=WINDOWS

[GAME2]
name=CALCULATOR
path=calc.exe
folder=WINDOWS

[GAME3]
name=DOOM
path=
folder=DOS

[GAME4]
name=SUPER MARIO WORLD
path=
folder=SNES